---

- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - pyyaml
    - bioblend

- name: Place the tool management script
  copy: src=install_tool_shed_tools.py dest={{ galaxy_tools_base_dir }}/install_tool_shed_tools.py

- name: Copy tool list file
  copy: src={{ galaxy_tools_tool_list_file }} dest={{ galaxy_tools_base_dir }}/tool_list.yaml

- name: Install Tool Shed tools
  command: chdir={{ galaxy_tools_base_dir }} {{ galaxy_tools_base_dir }}/venv/bin/python install_tool_shed_tools.py -t tool_list.yaml -a {{ galaxy_tools_api_key }} -g {{ galaxy_tools_galaxy_instance_url }}
  ignore_errors: true

- name: Remove tool management scripts/file
  file: dest={{ galaxy_tools_base_dir }}/{{ item }} state=absent
  with_items:
    - install_tool_shed_tools.py
    - tool_list.yaml
