---

- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - pyyaml
    - bioblend

- name: Place the tool management script
  copy: src=install_tool_shed_tools.py dest={{ galaxy_tools_base_dir }}/install_tool_shed_tools.py

- name: Copy tool list files
  copy: src={{ item }} dest={{ galaxy_tools_base_dir }}/{{ item|basename }}
  with_items: galaxy_tools_tool_list_files

- name: Install Tool Shed tools
  command: chdir={{ galaxy_tools_base_dir }} {{ galaxy_tools_base_dir }}/venv/bin/python install_tool_shed_tools.py -t {{ item|basename }} -a {{ galaxy_tools_api_key }} -g {{ galaxy_tools_galaxy_instance_url }}
  with_items: galaxy_tools_tool_list_files

- name: Remove tool list files
  file: dest={{ galaxy_tools_base_dir }}/{{ item|basename }} state=absent
  with_items: galaxy_tools_tool_list_files

- name: Remove tool management script
  file: dest={{ galaxy_tools_base_dir }}/install_tool_shed_tools.py state=absent