---

- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - https://github.com/galaxyproject/ephemeris/archive/master.zip

- include: install_tool_list.yml
  with_items: '{{ galaxy_tools_tool_list_files }}'
  loop_control:
    loop_var: tool_list_file
