---

- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - pyyaml
    - bioblend

- name: Place the tool management script
  copy: src=install_tool_shed_tools.py dest={{ galaxy_tools_base_dir }}/install_tool_shed_tools.py

- name: get tool list
  include_vars: "{{ galaxy_tools_tool_list }}"

- name: Install Tool Shed tools
  command: chdir={{ galaxy_tools_base_dir }} {{ galaxy_tools_base_dir }}/venv/bin/python install_tool_shed_tools.py -y "{{ item | to_nice_yaml }}" -a {{ galaxy_tools_api_key }} -g {{ galaxy_tools_galaxy_instance_url }}
  with_items:
    - "{{ tools }}"

- name: Remove tool management script
  file: dest={{ galaxy_tools_base_dir }}/install_tool_shed_tools.py state=absent
